[package]
name = "meep_squared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap="*"
nom="7"

[dependencies.uuid]
version="1.1.2"
features = [
    "v4"
]